[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.2"
wacz-signing = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
